services:
  vaccinacare.api:
    image: ${DOCKER_REGISTRY-}vaccinacareapi
    build:
      context: .
      dockerfile: VaccinaCare.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=Host=goodsdesignapi-database;Port=5432;Database=goodsdesignapi;Username=postgres;Password=YourStrong!Passw0rd;"

