services:
  vaccinacare-api:
    build:
      context: . # Thư mục gốc chứa Dockerfile
      dockerfile: VaccinaCare.API/Dockerfile
    image: phuctran362003/vaccinacareapi:latest
    ports:
      - "5000:5000"
    depends_on:
      - vaccinacare-database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=Server=103.211.201.162,1433;Database=VaccinaCareDb;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;Encrypt=False;MultipleActiveResultSets=True"
      - "JWT__SecretKey=VaccinaCare_SECRETKEY_SIEUCAPBAOMAT_VAYMACHUADU16KYTU"
      - "JWT__Issuer=VaccinaCare_Issuer"
      - "JWT__Audience=VaccinaCare_Audience"
      - "Payment__VnPay__ReturnUrl=https://vaccina-care-fe.vercel.app/payment-success"
      - "Payment__VnPay__PaymentUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
      - "Payment__VnPay__TmnCode=O7RXN745"
      - "Payment__VnPay__HashSecret=CTSEWKH8ZGNRYE8GYH9H4UW3H5W097HB"
      - EMAIL_USERNAME=trangiaphuc362003181@gmail.com
      - EMAIL_PASSWORD=hygd bzzo brzp knfm
      - EMAIL_HOST=smtp.gmail.com
      - MINIO_ENDPOINT=minio.ae-tao-fullstack-api.site:9000
      - MINIO_ACCESS_KEY=103.211.201.162
      - MINIO_SECRET_KEY=Ccubin2003@

  vaccinacare-database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: vaccinacare-database
    restart: always
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
    driver: local
